name: Terraform CI/CD

on:
  push:
    branches:
      - master # Trigger on push to the 'main' branch

jobs:
  terraform:
    name: Run Terraform
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/testingthecd:latest --push .

      #Install terra form on brum brum
      - name: Setting up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Set AWS Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=eu-west-1" >> $GITHUB_ENV
        shell: bash

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate

      # Plan Terraform deployment
      - name: Terraform Plan
        run: terraform plan

      # Apply Terraform configuration
      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Wait for 5 minutes before destroying resources
        run: sleep 300 # sleep for 300 seconds (5 minutes)

      # Destroy Terraform resources
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
